module.exports.run = async(client, message, args) => {
  message.delete()
  const Discord = require('discord.js')
  const permissions = require('./permissions.json')
  if(!message.member.roles.some(r => permissions.moderation.includes(r.id))) return message.channel.send('Vous n\'avez pas la permission d\'executer cette commande.')
  let muteRole = message.guild.roles.find(r => r.name === 'Muted')
  let unmuted = message.mentions.members.first()
  if(!unmuted) return message.channel.send('Vous devez spécifiez un utilisateur.')
  if(!unmuted.roles.find(r => r.name === 'Muted')) return message.channel.send('Cette utilisateur n\'est pas mute actuellement.')
  unmuted.removeRole(muteRole)
  const unmutedObject = await client.fetchUser(unmuted.id)
  let mutedChannelEmbed = new Discord.RichEmbed()
      .setAuthor(unmutedObject.username, unmutedObject.avatarURL)
      .setTitle('L\'utilisateur a bien été unmute')
   //   .addField('Duré', msToTime(muteTime))
  //    .addField('Utilisateur', toMuteUserObject.username)
      .setFooter('Pour le re-mute, utiliser la commande !mute')
      .setThumbnail(message.author.avatarURL)
    const sentM2 = await message.channel.send(mutedChannelEmbed)
    const sanctionsEmbed = new Discord.RichEmbed()
      .setAuthor(`Modérateur: ${message.author.tag}`, message.author.avatarURL)
      .setDescription(`
**Membre**: ${unmutedObject.tag} (${unmutedObject.id})
**Action**: Un-Mute
`)
      .setColor('#66ff66')
    const sanctionsChannel = message.guild.channels.find(c => c.id === '586583489382449162').send(sanctionsEmbed)
    sentM2.delete(5000)
}